name: "linearsvr_baseline"
model: "linearsvr"
metric: "mse"
mode: "min"
strategy: "grid"

base_model_params:
  fit_intercept: true
  max_iter: 1000
  tol: 0.0001
  random_state: 42
  dual: true

params:
  C: [0.1, 1.0, 10.0]
  epsilon: [0.0, 0.1, 0.2]
  loss: ["epsilon_insensitive", "squared_epsilon_insensitive"]
