name: "svr_baseline"
model: "svr"
metric: "mse"
mode: "min"
strategy: "grid"

base_model_params:
  shrinking: true
  tol: 0.001
  max_iter: -1

params:
  kernel: ["rbf", "linear"]     # you can add "poly" later if you like
  C: [0.1, 1.0, 10.0]
  epsilon: [0.01, 0.1]
  gamma: ["scale", "auto"]
