name: "ada_baseline"
model: "ada"
metric: "mse"
mode: "min"
strategy: "grid"

base_model_params:
  random_state: 42

params:
  n_estimators: [50, 100, 200]
  learning_rate: [0.01, 0.1, 0.5, 1.0]
  loss: ["linear", "square", "exponential"]
