name: "hgb_baseline"
model: "hgb"
metric: "mse"
mode: "min"
strategy: "grid"

base_model_params:
  loss: "squared_error"
  random_state: 42

params:
  max_iter: [100, 200]
  learning_rate: [0.05, 0.1]
  max_leaf_nodes: [31, 63, 127]
  max_depth: [null, 5, 10]
  min_samples_leaf: [10, 20, 40]
  l2_regularization: [0.0, 0.1]
