name: "gamma_baseline"
model: "gamma"
metric: "mse"
mode: "min"
strategy: "grid"

base_model_params:
  max_iter: 1000
  tol: 0.00001
  warm_start: false
  verbose: 0

params:
  alpha: [0.0, 0.01, 0.1, 1.0]
  fit_intercept: [true, false]
