name: "tweedie_baseline"
model: "tweedie"
metric: "mse"
mode: "min"
strategy: "grid"

base_model_params:
  max_iter: 1000
  tol: 1e-4
  link: "log"
  warm_start: false

params:
  power: [1.1, 1.3, 1.5, 1.8]  # 1.1≈Poisson-like, 1.8≈Gamma-like
  alpha: [0.0, 0.01, 0.1]      # regularization
  fit_intercept: [true, false]
