name: "extratrees_baseline"
model: "extratrees"
metric: "mse"
mode: "min"
strategy: "grid"

base_model_params:
  n_estimators: 200
  random_state: 42
  n_jobs: -1
  bootstrap: false

params:
  max_depth: [null, 5, 10, 20]
  max_features: ["sqrt", "log2", null]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]
