name: "lars_baseline"
model: "lars"
metric: "mse"
mode: "min"
strategy: "grid"

base_model_params:
  fit_intercept: true
  # you can add 'eps' here if you want, but default is fine

params:
  n_nonzero_coefs: [3, 5, 8, 12]
  # optionally:
  # fit_intercept: [true, false]


