model:
  name: "perceptron_classifier"
  library: "sklearn"
  type: "perceptron"     # must match your registry key / CLI: --model perceptron
  params:
    # Perceptron(**params)
    penalty: null        # null | "l2" | "l1" | "elasticnet"
    alpha: 0.0001
    l1_ratio: 0.15
    fit_intercept: true
    max_iter: 1000
    tol: 0.001
    shuffle: true
    early_stopping: false
    validation_fraction: 0.1
    n_iter_no_change: 5
    class_weight: null   # set to "balanced" if needed
    random_state: 42
    warm_start: false

preprocessing:
  # Perceptron is sensitive to feature scale
  scale_numeric: true

collinearity:
  enabled: true
  mode: "manual"
  pipeline: ["pearson"]

  pearson:
    abs_threshold: 0.99

mlflow:
  log_collinearity_diagnostics: true
  log_vif_table: false
  log_correlation_heatmap: false
  log_svd_spectrum: false
