name: "theilsen_baseline"
model: "theilsen"
metric: "mse"
mode: "min"
strategy: "grid"

base_model_params:
  fit_intercept: true
  copy_X: true
  random_state: 42
  n_jobs: -1

params:
  max_subpopulation: [10000, 50000]
  n_subsamples: [null, 200]        # None â†’ heuristic, or fixed 200
  max_iter: [100, 300]
  tol: [0.001, 0.0001]
