name: local
tracking_uri: http://127.0.0.1:5000
experiment: bike_regression
registry_uri: null        # or e.g. 'sqlite:///mlflow.db' if you use registry
autolog: false            # if you want main.py to enable/disable autolog
