name: "ransac_baseline"
model: "ransac"
metric: "mse"
mode: "min"
strategy: "grid"

base_model_params:
  max_skips: 1000
  stop_probability: 0.99
  random_state: 42

params:
  min_samples: [0.3, 0.5, 0.7]          # fraction of samples
  residual_threshold: [5.0, 10.0, 20.0] # depends on your target scale
  max_trials: [100, 200]
  loss: ["absolute_loss", "squared_loss"]
